import type { Locale } from "../content/profileContent";

export function getSyncKitText(locale: Locale) {
  return locale === "pt-BR"
    ? {
        assistedIntegration: "Integração Assistida",
        syncKitTitle: "Sync Kit para GitHub e LinkedIn",
        syncKitBody:
          "Este painel organiza os dados de perfil em um formato pronto para atualização manual com checkpoint humano. Nenhuma alteração é submetida automaticamente em plataformas externas.",
        payloadSnapshot: "Snapshot do payload",
        name: "Nome",
        location: "Localização",
        company: "Empresa atual",
        checkpoint: "Checkpoint humano",
        required: "obrigatório",
        no: "não",
        usage: "Uso",
        waitingPayload: "Aguardando leitura de profile-sync-payload.json.",
        diffMatrix: "Matriz de diferença",
        expectedObserved: "Esperado vs observado",
        expectedObservedBody:
          "Preencha os valores atualmente visíveis em GitHub e LinkedIn para validar convergência antes do checkpoint humano de publicação.",
        readinessSummary: "Resumo de prontidão",
        fieldsEvaluated: "campos avaliados",
        ready: "pronto para checkpoint humano",
        pending: "ainda pendente",
        divergentPending: "Pendências divergentes",
        noDivergence: "Nenhuma divergencia detectada.",
        nonEvaluatedPending: "Pendências não avaliadas",
        fillObserved: "Acao: preencher valor observado no formulario.",
        allEvaluated: "Todos os campos ja foram avaliados.",
        observedValues: "Valores observados (entrada manual)",
        compareResult: "Resultado da comparação",
        expected: "Esperado",
        observed: "Observado",
        clearSnapshot: "Limpar snapshot observado",
        exportDiagnostic: "Exportar diagnóstico MD",
        checklist: "Checklist rapido",
        checklist1: "Confirmar headline PT-BR e EN antes de publicar",
        checklist2:
          "Confirmar website do GitHub apontando para a frontpage publicada",
        checklist3: "Confirmar links de CV PT-BR e EN funcionando",
        checklist4:
          "Realizar checkpoint humano antes de salvar qualquer alteração",
        openReadmeSnippet: "Abrir snippet README",
        openReviewTemplate: "Abrir template de revisão",
        readyTexts: "Textos prontos para uso",
        githubBioSuggestion: "Sugestao GitHub Bio",
        openGithubProfile: "Abrir GitHub Profile",
        linkedinAboutSuggestion: "Sugestao LinkedIn About (EN)",
        openLinkedinProfile: "Abrir LinkedIn Profile",
        targetRolesPt: "Roles alvo PT-BR",
        targetRolesEn: "Target roles EN",
      }
    : {
        assistedIntegration: "Assisted Integration",
        syncKitTitle: "Sync Kit for GitHub and LinkedIn",
        syncKitBody:
          "This panel organizes profile data in a format ready for manual updates with a human checkpoint. No changes are submitted automatically to external platforms.",
        payloadSnapshot: "Payload snapshot",
        name: "Name",
        location: "Location",
        company: "Current company",
        checkpoint: "Human checkpoint",
        required: "required",
        no: "no",
        usage: "Usage",
        waitingPayload: "Waiting for profile-sync-payload.json.",
        diffMatrix: "Difference matrix",
        expectedObserved: "Expected vs observed",
        expectedObservedBody:
          "Fill in the values currently visible in GitHub and LinkedIn to validate convergence before the human publishing checkpoint.",
        readinessSummary: "Readiness summary",
        fieldsEvaluated: "evaluated fields",
        ready: "ready for human checkpoint",
        pending: "still pending",
        divergentPending: "Divergent pending items",
        noDivergence: "No divergence detected.",
        nonEvaluatedPending: "Not evaluated pending items",
        fillObserved: "Action: fill in the observed value in the form.",
        allEvaluated: "All fields are already evaluated.",
        observedValues: "Observed values (manual input)",
        compareResult: "Comparison result",
        expected: "Expected",
        observed: "Observed",
        clearSnapshot: "Clear observed snapshot",
        exportDiagnostic: "Export MD diagnostic",
        checklist: "Quick checklist",
        checklist1: "Confirm PT-BR and EN headline before publishing",
        checklist2: "Confirm GitHub website points to the published frontpage",
        checklist3: "Confirm PT-BR and EN CV links are working",
        checklist4: "Perform human checkpoint before saving any change",
        openReadmeSnippet: "Open README snippet",
        openReviewTemplate: "Open review template",
        readyTexts: "Ready-to-use texts",
        githubBioSuggestion: "GitHub Bio suggestion",
        openGithubProfile: "Open GitHub Profile",
        linkedinAboutSuggestion: "LinkedIn About suggestion (EN)",
        openLinkedinProfile: "Open LinkedIn Profile",
        targetRolesPt: "Target roles PT-BR",
        targetRolesEn: "Target roles EN",
      };
}
